### ISSUE TITLE
Error on launch: 'Unable to execute script at line 687. Not well-formed (invalid token)'

### ISSUE THREAD

**Issue by jordanlloyd** [Hyle-Script/Hyle#1]
I get this error on launch, 'Unable to execute script at line 687. Not well-formed (invalid token)' when attempting to run it in CC 2015.

**Comment by seblavoie** [comment]
Okay, I will need a bit more detail to reproduce the bug. Line 687 would be a weird place to cause a bug, but let's try to understand what's going on.
- What system do you run it on?
- Do you have the latest version?
- Do you have something else in your startup scripts folder? 

In your After Effects preferences:
- Do you have “Allow Scripts to Write Files and Access Network” checked? (If not, check it and restart, it might just fix it).
- Do you have “Enable Javascript Debugger” checked? (If not, check it and restart it might give us more information).

**Comment by jordanlloyd** [comment]
Hey man,

Must have had an older version in there or something, just tried
redownloading again and now everything looks to be working again with no
problems. Pretty sure I had already done that but apparently not, so chalk
this one up to pilot error... sorry for the false alarm!

On Wed, Aug 12, 2015 at 10:12 PM, Sébastien Lavoie <notifications@github.com

**Comment by seblavoie** [comment]
Great, no problem. Glad to know it worked out! 👌
